src/Entity/Proyectos.php
<?php

namespace App\Entity;

use App\Repository\ProyectosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProyectosRepository::class)]
class Proyectos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\ManyToOne(inversedBy: 'proyectos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Sedes $sede = null;

    #[ORM\Column(length: 100)]
    private ?string $zonaActuacion = null;

    #[ORM\Column]
    private ?int $totalGasto = null;

    #[ORM\Column]
    private ?int $personalVinculado = null;

    #[ORM\Column]
    private ?int $totalParticipantes = null;

    #[ORM\Column]
    private ?int $totalVoluntarios = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fechaInicio = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fechaFinal = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'proyectos')]
    private Collection $users;

    #[ORM\OneToMany(mappedBy: 'proyecto', targetEntity: Gasto::class, orphanRemoval: true)]
    private Collection $gastos;

    #[ORM\Column(length: 50)]
    private ?string $Activo = null;

    #[ORM\OneToMany(mappedBy: 'proyecto', targetEntity: Ingreso::class)]
    private Collection $ingresos;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $ingresosTotales = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->gastos = new ArrayCollection();
        $this->ingresos = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getSede(): ?Sedes
    {
        return $this->sede;
    }

    public function setSede(?Sedes $sede): self
    {
        $this->sede = $sede;

        return $this;
    }

    public function getZonaActuacion(): ?string
    {
        return $this->zonaActuacion;
    }

    public function setZonaActuacion(string $zonaActuacion): self
    {
        $this->zonaActuacion = $zonaActuacion;

        return $this;
    }

    public function getTotalGasto(): ?int
    {
        return $this->totalGasto;
    }

    public function setTotalGasto(int $totalGasto): self
    {
        $this->totalGasto = $totalGasto;

        return $this;
    }

    public function getPersonalVinculado(): ?int
    {
        return $this->personalVinculado;
    }

    public function setPersonalVinculado(int $personalVinculado): self
    {
        $this->personalVinculado = $personalVinculado;

        return $this;
    }

    public function getTotalParticipantes(): ?int
    {
        return $this->totalParticipantes;
    }

    public function setTotalParticipantes(int $totalParticipantes): self
    {
        $this->totalParticipantes = $totalParticipantes;

        return $this;
    }

    public function getTotalVoluntarios(): ?int
    {
        return $this->totalVoluntarios;
    }

    public function setTotalVoluntarios(int $totalVoluntarios): self
    {
        $this->totalVoluntarios = $totalVoluntarios;

        return $this;
    }

    public function getFechaInicio(): ?\DateTimeInterface
    {
        return $this->fechaInicio;
    }

    public function setFechaInicio(\DateTimeInterface $fechaInicio): self
    {
        $this->fechaInicio = $fechaInicio;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getFechaFinal(): ?\DateTimeInterface
    {
        return $this->fechaFinal;
    }

    /**
     * @param \DateTimeInterface|null $fechaFinal
     */
    public function setFechaFinal(?\DateTimeInterface $fechaFinal): void
    {
        $this->fechaFinal = $fechaFinal;
    }



    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Gasto>
     */
    public function getGastos(): Collection
    {
        return $this->gastos;
    }

    public function addGasto(Gasto $gasto): self
    {
        if (!$this->gastos->contains($gasto)) {
            $this->gastos->add($gasto);
            $gasto->setProyecto($this);
        }

        return $this;
    }

    public function removeGasto(Gasto $gasto): self
    {
        if ($this->gastos->removeElement($gasto)) {
            // set the owning side to null (unless already changed)
            if ($gasto->getProyecto() === $this) {
                $gasto->setProyecto(null);
            }
        }

        return $this;
    }

    public function getActivo(): ?string
    {
        return $this->Activo;
    }

    public function setActivo(string $Activo): self
    {
        $this->Activo = $Activo;

        return $this;
    }

    /**
     * @return Collection<int, Ingreso>
     */
    public function getIngresos(): Collection
    {
        return $this->ingresos;
    }

    public function addIngreso(Ingreso $ingreso): self
    {
        if (!$this->ingresos->contains($ingreso)) {
            $this->ingresos->add($ingreso);
            $ingreso->setProyecto($this);
        }

        return $this;
    }

    public function removeIngreso(Ingreso $ingreso): self
    {
        if ($this->ingresos->removeElement($ingreso)) {
            // set the owning side to null (unless already changed)
            if ($ingreso->getProyecto() === $this) {
                $ingreso->setProyecto(null);
            }
        }

        return $this;
    }

    public function getIngresosTotales(): ?string
    {
        return $this->ingresosTotales;
    }

    public function setIngresosTotales(string $ingresosTotales): self
    {
        $this->ingresosTotales = $ingresosTotales;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use Flasher\Prime\FlasherInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ProyectosRepository;
use App\Repository\SedesRepository;
use Doctrine;
use App\Repository\UserRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

class DashboardController extends AbstractController
{
    #[Route('/dashboard', name: 'app_dashboard')]
    public function index(ChartBuilderInterface $chartBuilder,SedesRepository $sedes, UserRepository $users, ProyectosRepository $proyectos): Response
    {

        $ahora = new \DateTime((date('d-m-Y H:i:s')));

        $allSedes = $sedes->findAll();
        $allUsers = $users->findAll();

        $allProyectos = $proyectos->findAll();
        $totalSedes = sizeof($allSedes);
        $totalProyectos = sizeof($allProyectos);
        $totalUsuarios = sizeof($allUsers);


        return $this->render('dashboard/index.html.twig', ['sedes' => $allSedes, 'ahora'=> $ahora, 'usuarios' => $allUsers, 'proyectos' => $allProyectos,
            'totalSedes' => $totalSedes, 'totalProyectos' => $totalProyectos, 'totalUsuarios' => $totalUsuarios]);

    }
    #[Route('/dashboardSedes', name: 'dashboard_sedes')]
    public function dashboardSedes(SedesRepository $sedes, UserRepository $users, ProyectosRepository $proyectos): Response
    {
        $allSedes = $sedes->findAll();
        $allUsers = $users->findAll();
        $allProyectos = $proyectos->findAll();
        $totalSedes = sizeof($allSedes);


        return $this->render('dashboard/sedes.html.twig', ['sedes' => $allSedes,  'totalSedes' => $totalSedes]);

    }
    /**
     * @IsGranted("ROLE_ADMIN_SEDES")
     */
    #[Route('/dashboardMiSede', name: 'dashboard_Misede')]
    public function dashboardMiSede(SedesRepository $sedes, UserRepository $users, ProyectosRepository $proyectos): Response
    {
        $tieneSede=true;
        $user=$this->getUser();
        $idUser=$user->getId();
        $sede=$sedes->findOneBy(array('administradorSede' => $idUser));
        if(is_null($sede)){
            $tieneSede=false;
            $proyectos=null;
            $totalProyectos=null;
        }else{
            $proyectos=$sede->getProyectos();
            $totalProyectos=sizeof($proyectos);
        }


        return $this->render('dashboard/miSede.html.twig', ['ac' => $sede, 'totalProyectos' => $totalProyectos, 'proyectos' => $proyectos, 'tieneSede'=>$tieneSede]);

    }

    #[Route('/dashboardProyectos', name: 'dashboard_proyectos')]
    public function dashboardProyectos(SedesRepository $sedes, UserRepository $users, ProyectosRepository $proyectos): Response
    {
        $allSedes = $sedes->findAll();
        $allUsers = $users->findAll();
        $allProyectos = $proyectos->findAll();
        $totalProyectos = sizeof($allProyectos);


        return $this->render('dashboard/proyectos.html.twig', ['proyectos' => $allProyectos,  'totalProyectos' => $totalProyectos]);

    }

    /**
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_ADMIN_SEDES')")
     */
    #[Route('/dashboardTodosUsuarios', name: 'dashboard_todosUsuarios')]
    public function dashboardUsuarios(SedesRepository $sedes, UserRepository $users, ProyectosRepository $proyectos): Response
    {
        $allUsers = $users->findAll();
        $usuarios= sizeof($users->findBy(array('rol' => 'Usuario')));
        $voluntarios= sizeof($users->findBy(array('rol' => 'Voluntario')));
        $adSedes= sizeof($users->findBy(array('rol' => 'Administrador de sede')));

        return $this->render('dashboard/dashboardUsuarios.html.twig', ['usuarios' => $allUsers, 'nUsuarios'=>$usuarios, 'nVoluntarios'=>$voluntarios, 'nSedes'=>$adSedes]);

    }
    /**
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_ADMIN_SEDES')")
     */
    #[Route('/dashboardTodosUsuariosAdminSedes', name: 'dashboard_todosUsuariosAdminSedes')]
    public function dashboardUsuariosAdminSedes(SedesRepository $sedes, UserRepository $users, ProyectosRepository $proyectos): Response
    {
        //$allUsers = $users->findAll();
        $usuarios= $users->findBy(array('rol' => 'Administrador de sede'));


        return $this->render('dashboard/dashboardUsuariosAdminSedes.html.twig', ['usuarios' => $usuarios]);

    }
    /**
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_ADMIN_SEDES')")
     */
    #[Route('/dashboardTodosUsuariosVoluntarios', name: 'dashboard_todosUsuariosVoluntarios')]
    public function dashboardUsuariosVoluntarios(SedesRepository $sedes, UserRepository $users, ProyectosRepository $proyectos): Response
    {
        //$allUsers = $users->findAll();
        $usuarios= $users->findBy(array('rol' => 'Voluntario'));


        return $this->render('dashboard/dashboardUsuariosVoluntarios.html.twig', ['usuarios' => $usuarios]);

    }
    /**
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_ADMIN_SEDES')")
     */
    #[Route('/dashboardTodosUsuariosParticipantes', name: 'dashboard_todosUsuariosParticipantes')]
    public function dashboardUsuariosParticipantes( UserRepository $users): Response
    {
        //$allUsers = $users->findAll();
        $usuarios= $users->findBy(array('rol' => 'Usuario'));


        return $this->render('dashboard/dashboardUsuariosParticipantes.html.twig', ['usuarios' => $usuarios]);

    }
    /**
     * @Security("is_granted('ROLE_ADMIN')")
     * @Route("/eliminar_sede", options={"expose"=true}, methods={"POST"}, name="eliminar_sede")
     */
    public function eliminarSede(Request $request, Doctrine\Persistence\ManagerRegistry $doctrine, SedesRepository $sedes, ProyectosRepository $proyectos){

        if ($request->isXmlHttpRequest()){
            $id=$request->get('id');
            $em= $doctrine->getManager();
            $sede=$sedes->find(array('id' => $id));
            $adminSede=$sede->getAdministradorSede();
            if(!(is_null($adminSede))){
                $adminSede->setTieneSedeAdministrada(0);
            }
            $sede->setAdministradorSede(null);
            $proyectosSede=$sede->getProyectos();
            foreach($proyectosSede as $proyecto){
                $users=$proyecto->getUsers();
                foreach($users as $user){
                    $proyecto->removeUser($user);
                }
                $gastos=$proyecto->getGastos();
                foreach($gastos as $gasto){
                    $proyecto->removeGasto($gasto);
                }
                $ingresos=$proyecto->getIngresos();
                foreach($ingresos as $ingreso){
                    $proyecto->removeIngreso($ingreso);
                }
                $proyectos->remove($proyecto);
            }
            $nombre=$sede->getNombre();
            $sedes->remove($sede);
            $em->flush();
            return new JsonResponse(['nombre' =>$nombre]);
        }else{
            throw new \Exception('No se ha podido eliminar la sede');
        }
    }
    /**
     * @Security("is_granted('ROLE_ADMIN_SEDES')")
     * @Route("/eliminar_proyecto", options={"expose"=true}, methods={"POST"}, name="eliminar_proyecto")
     */
    public function eliminarProyecto(Request $request, Doctrine\Persistence\ManagerRegistry $doctrine,  ProyectosRepository $proyectos){
        if ($request->isXmlHttpRequest()){
            $id=$request->get('id');
            $em= $doctrine->getManager();
            $proyecto=$proyectos->find(array('id' => $id));
            $sede=$proyecto->getSede();
            $users=$proyecto->getUsers();
            foreach($users as $user){
                $proyecto->removeUser($user);
            }
            $gastos=$proyecto->getGastos();
            foreach($gastos as $gasto){
                $proyecto->removeGasto($gasto);
            }
            $ingresos=$proyecto->getIngresos();
            foreach($ingresos as $ingreso){
                $proyecto->removeIngreso($ingreso);
            }
            $sede->removeProyecto($proyecto);
            $proyectos->remove($proyecto);

            $em->flush();
            return new JsonResponse(['nombre']);
        }else{
            throw new \Exception('No se ha podido eliminar el proyecto');
        }
    }
}

templates/dashboard/index.html.twig
{% extends 'navegador.html.twig' %}

{% block title %}
    {{ parent() }} - Dashboard
{% endblock %}
{% block stylesheets %}



    <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}">
    <link href="{{ asset('vendor/fonts/circular-std/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('libs/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/fonts/fontawesome/css/fontawesome-all.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/dataTables.bootstrap4.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/buttons.bootstrap4.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/select.bootstrap4.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/fixedHeader.bootstrap4.css') }}">
{% endblock %}

{% block body %}
    {{ parent() }}
    <!-- ============================================================== -->
    <!-- wrapper  -->
    <!-- ============================================================== -->
    <div class="dashboard-wrapper">
        <div class="dashboard-ecommerce">
            <div class="container-fluid dashboard-content ">
                <!-- ============================================================== -->
                <!-- pageheader  -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="page-header">
                            <h2 class="pageheader-title"></h2>
                            <div class="page-breadcrumb">
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="/dashboard" class="breadcrumb-link">Dashboard</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Inicio</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                {% for message in app.flashes('exitoCategoriaGasto') %}
                    <div class="row">
                        <div class="col-xl-11 col-lg-11 col-md-11 col-sm-11 col-11">
                            <div class="alert alert-success">
                                {{ message }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="row justify-content-md-center" style="margin-bottom: 5%;">

                    <div id="pestanas" class="">
                        <ul id=lista>
                            <li id="pestana1"><a href='javascript:cambiarPestanna(pestanas,pestana1);'>Sedes</a></li>
                            <li id="pestana2"><a href='javascript:cambiarPestanna(pestanas,pestana2);'>Usuarios</a></li>
                            <li id="pestana3"><a href='javascript:cambiarPestanna(pestanas,pestana3);'>Proyectos</a></li>
                        </ul></div>

                    <body onload="javascript:cambiarPestanna(pestanas,pestana1);">

                    <div id="contenidopestanas">
                        <main id="cpestana1">
                            <table class="table first">
                                <thead class="bg-light">
                                <tr class="border-0">
                                    <th class="border-0">Nombre</th>
                                    <th class="border-0">Localización</th>
                                    <th class="border-0">Acciones</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for ac in sedes %}
                                    <tr>
                                        <td>{{ ac.nombre }}</td>
                                        <td>{{ ac.localizacion }}</td>
                                        <td>
                                            {% if app.user.getRol() == "Administrador"  %}
                                            <button onclick="eliminarSede({{ ac.id }})" title="Eliminar sede" class="btn  p-1 rounded fa-lg my-1" style="background-color: #da0419;"><i class="fas fa-trash-alt" aria-hidden="true"></i></button>
                                            <button  onclick="window.location.href='{{ path('editar_sede',{id:ac.id}) }}'" title="Editar sede" class="btn  p-1 rounded fa-lg my-1" style="background-color: #f3b600;"><i class="fas fa-edit"></i></button>
                                            {% endif %}
                                            <button title="Ver sede"  onclick="window.location.href='{{ path('verSede',{id:ac.id}) }}'" class="btn  p-1 rounded fa-lg my-1" style="background-color: green;"><i class="fas fa-eye"></i></button> </td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </main>
                        <main id="cpestana2">
                            <table class="table table-striped table-bordered first">
                                <thead class="bg-light ">
                                <tr class="border-0" >
                                    <th class="border-0">Nombre</th>
                                    <th class="border-0">Apellidos</th>
                                    <th class="border-0">Fecha de nacimiento</th>
                                    <th class="border-0">Sexo</th>
                                    <th class="border-0">Nacionalidad</th>
                                    <th class="border-0">Estado civil</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for ac in usuarios %}
                                    <tr class="selectHover"  onclick="window.location.href='{{ path('verUsuario',{id:ac.id}) }}'" style="cursor: pointer;">
                                        <td >{{ ac.nombre }}</td>
                                        <td >{{ ac.apellidos }}</td>
                                        <td>{{ ac.fechaNacimiento | date('d-m-Y') }}</td>
                                        <td>{{ ac.sexo }}</td>
                                        <td>{{ ac.nacionalidad }}</td>
                                        <td>{{ ac.estadoCivil }}</td>


                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </main>
                        <main id="cpestana3">
                            <table class="table table-striped table-bordered first">
                                <thead>
                                <tr >
                                    <th class="border-0">Nombre</th>
                                    <th class="border-0">Sede del proyecto</th>
                                    <th class="border-0">Zona de actuación</th>
                                    <th class="border-0">Total de participantes</th>
                                    <th class="border-0">Gasto total</th>
                                    <th class="border-0">Fecha de inicio</th>
                                    <th class="border-0">Actividad</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for ac in proyectos %}
                                    <tr class="selectHover"  onclick="window.location.href='{{ path('verProyecto',{id:ac.id}) }}'" style="cursor: pointer;">
                                        <td>{{ ac.nombre }}</td>
                                        <td>{{ ac.sede.localizacion }}</td>
                                        <td>{{ ac.zonaActuacion }}</td>
                                        <td>{{ ac.totalParticipantes }}</td>
                                        <td>{{ ac.totalGasto }} €</td>
                                        <td>{{ ac.fechaInicio  | date('d-m-Y')}}</td>
                                        {% if ac.activo == "Activo" %}
                                            <td style="color: green;"><b>• {{ ac.activo }}</b></td>
                                        {% else %}
                                            <td style="color: red;"><b>• {{ ac.activo }}</b></td>
                                        {% endif %}
                                            </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </main>
                    </div>

                </div>

            </div>
        </div>

        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                        Organización Social © 2022 Concept. Panel de administración.
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                        <div class="text-md-right footer-links d-none d-sm-block">
                            <a href="javascript: void(0);">Sobre Nosotros</a>
                            <a href="javascript: void(0);">Soporte</a>
                            <a href="javascript: void(0);">Contacto</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end footer -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- end wrapper  -->
    <!-- ============================================================== -->
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('libs/js/main-js.js') }}"></script>
    <script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
    <script src="{{ path('fos_js_routing_js',{callback: 'fos.Router.setData'}) }}"></script>
    <script src="{{ asset('js/ajax-call.js') }}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{{ asset('vendor/jquery/jquery-3.3.1.min.js') }}"></script>¡
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('vendor/datatables/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/js/data-table.js') }}"></script>
    <script src="https://cdn.datatables.net/rowgroup/1.0.4/js/dataTables.rowGroup.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.2.7/js/dataTables.select.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

    <script type="text/javascript">
        function cambiarPestanna(pestannas,pestanna) {

            pestanna = document.getElementById(pestanna.id);
            listaPestannas = document.getElementById(pestannas.id);

            cpestanna = document.getElementById('c'+pestanna.id);
            listacPestannas = document.getElementById('contenido'+pestannas.id);

            i=0;
            while (typeof listacPestannas.getElementsByTagName('main')[i] != 'undefined'){
                $(document).ready(function(){
                    $(listacPestannas.getElementsByTagName('main')[i]).css('display','none');
                    $(listaPestannas.getElementsByTagName('li')[i]).css('background','');
                    $(listaPestannas.getElementsByTagName('li')[i]).css('padding-bottom','');
                });
                i += 1;
            }

            $(document).ready(function(){
                $(cpestanna).css('display','');
                $(pestanna).css('background','dimgray');
                $(pestanna).css('padding-bottom','2px');
            });

        }


    </script>


{% endblock %}